name: Version

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ github.repository_owner == 'WaspScripts' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Git
        run: |
          git config --global user.name "Wasp Bot"
          git config --global user.email "waspbot@waspcripts.com"

      - name: Get current date
        id: date
        run: |
          echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV
          echo "CURRENT_MONTH=$(date +'%m')" >> $GITHUB_ENV
          echo "CURRENT_DAY=$(date +'%d')" >> $GITHUB_ENV

      - name: Update version in tauri.conf.json
        run: |
          VERSION="${CURRENT_YEAR}.${CURRENT_MONTH}.${CURRENT_DAY}-${COMMIT_HASH}"
          jq --arg ver "$VERSION" '.version = $ver' src-tauri/tauri.conf.json > tmp.json && mv tmp.json src-tauri/tauri.conf.json

      - name: Push changes to main branch
        run: |
          git add version.simba
          git commit -m "Automatic version bump to $CURRENT_YEAR.$CURRENT_MONTH.$CURRENT_DAY-$COMMIT_HASH" || echo "No changes to commit on main"
          git push
